config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  resources :categories
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	# Authors can produce multiple books.
	has_many :books

	# Authors can belong to many publishers throughout their life time.
	has_many :publishers 
end

app/models/book.rb
# Associations for the Book model
class Book < ApplicationRecord
  # Book can belong to one user.
  belongs_to :user 
  
  # Multiple authors can publish a book.
  has_many :authors
  
  # Book can only belong to one category.
  belongs_to :category
  
  # A book can have many reviews.
  has_many :reviews
  
  # Can only have one attached image of the book.
  has_one_attached :book_image
end

app/models/category.rb
class Category < ApplicationRecord
  # Association for the Category model
  has_many :books # One category has many books
end

app/models/publisher.rb
class Publisher < ApplicationRecord
	# Can have many authors working for them.
	has_many :authors
	
	# Publishers can publish many books.
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  # Reviews can belong to a book.
  belongs_to :book
  # Reviews can belong to a user.
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books # User can have many books.
  has_many :reviews # User can have many reviews.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	
	def index
	end

	def show
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  # General index for the application. This is where you see the overview of books.
  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @cateogory_id).order("created_at DESC")
    end
  end

  # For showing a book or books.
  def show
  end

  def new
    #@book = Book.new
    @book = current_user.books.build
    # This will map all of the categories for me and put them into a drop down.
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    #@book = Book.new(book_params)
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]
    @book.book_image.attach(params[:book][:book_image])

    # If save is intiated, redirect to the root path to see the new book.
    if @book.save
      redirect_to root_path
    else
      # Else you will re-render the new page.
      render 'new'
    end
  end

  # For editing books
  def edit
    # Load all of the categories so you can changed them for he book.
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # For updating a book.
  def update
    @book.category_id = params[:category_id]
    @book.book_image.purge
    @book.book_image.attach(params[:book_image])
    if @book.update(book_params)
      # Will redirect to the book's show page so you can view it.
      redirect_to book_path(@book)
    else
      # Else you will re-render the edit page.
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  # Private method for hidden parameters.
  private
    # These are the book_params for the appliation. These are required if the user is to view, edit, or destroy a book.
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :publish_date, :book_price, :page_count, :isbn_10, :isbn_13, :description, :category_id, :book_image)
    end

    # The find_book method for the application. This will find all of the books for you.
    def find_book
      @book = Book.find(params[:id])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def find_category
      @category = Category.find(params[:id])
    end

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_edit-book-form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :book_image, id: "item_item_img" %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :publisher %>
  <%= f.input :publish_date %>
  <%= f.input :book_price %>
  <%= f.input :page_count %>
  <%= f.input :isbn_10 %>
  <%= f.input :isbn_13 %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn-custom" %>
 <% end %>

app/views/books/_new-books-form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :book_image, id: "item_item_img" %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :publisher %>
  <%= f.input :publish_date %>
  <%= f.input :book_price %>
  <%= f.input :page_count %>
  <%= f.input :isbn_10 %>
  <%= f.input :isbn_13 %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn-custom" %>
<% end %>

app/views/books/edit.html.erb
<div class="item-form">
	<h1>Edit Book</h1>
	<%= render 'edit-book-form' %>
</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>
<% if @books.count == 0 %>
		<div class="row">
			<% @books.each do |book| %>
			<div class="col-md-3 book">
				<%= link_to image_tag(book.book_image, alt: 'book.title', class: "books"), book %>
			</div>
	  	<% end %>
	</div>
<% else %>
  <!---<div class="row">--->
	  <% @books.each do |book| %>
	   <div class="row">
	    <div class="col-md-3">
	    	<%= link_to image_tag(book.book_image, alt: 'book.title', class: "books"), book %>
	    </div>
	  <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="item-form">
	<h1>New Book</h1>
	<%= render 'new-books-form' %>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
      <%= image_tag @book.book_image, class: "book-show"  %>
      <% if user_signed_in? %>
        <% if @book.user_id == current_user.id %>
          <%= link_to "Edit Book", edit_book_path(@book), class: "btn-custom" %>
          <%= link_to "Delete Book", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-custom" %>
        <% end %>
      <% end %>
      <%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom links" %>
      <%= render @book.reviews %>
  </div>
  <div class="col-md-8 item-info">
    <h1 class="item-title"><%= @book.title %></h1>
    <h3 class="item-author">By <%= @book.author %></h3>
    <h4 class="item-author">Publisher(s): <%= @book.publisher %></h4>
    <h4 class="item-author">Publish Date: <%= @book.publish_date %></h4>
    <h4 class="item-author">Book Price: <%= @book.book_price %></h4>
    <h4 class="item-author">Page Count: <%= @book.page_count %></h4>
    <h4 class="item-author">ISBN 10: <%= @book.isbn_10 %></h4>
    <h4 class="item-author">ISBN-13: <%= @book.isbn_13 %></h4>
    <!--- <h4>Category: <%# @book.category.name %></h4> --->
    <h3 class="item-author">Book Summary:</h3>
    <p class="item-desc"><%= @book.description %></p>
  </div>
</div>


<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/categories/_categories-form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn-custom" %>
<% end %>

app/views/categories/edit.html.erb
<div class="edit-item-form">
	<h1>Edit Category</h1>
	<%= render 'categories-form' %>
</div>

app/views/categories/index.html.erb
<div class="row">
	<div class="item-info">
	  <h1 class="item-title">Categories List</h1>
	  <% @categories.each do |category| %>
	    <h3><%= category.name %></h3><br/>
	    <%= link_to "Edit Category", edit_category_path(category), class: "btn-custom" %>
	    <%= link_to "Delete Category", category_path(category), method: :delete, data: { confirm: "Are you sure you want to delete this category?"}, class: "btn-custom" %>
	  <% end %>
	</div>
</div>

app/views/categories/new.html.erb
<div class="item-form">
  <h2>New Category</h2>
  <%= render 'categories-form' %>
</div>

app/views/categories/show.html.erb
<div class="book-info">
  <h1>Categories List</h1>
  <% @categories.each do |category| %>
    <%= category.name %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Library & Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default is-dark has-text-white">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Book Library & Inventory", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>"><%= link_to category.name, books_path(category: category.name), class: "link" %></li>
              <% end %>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to sign out?"} %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Book Actions<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Add Book", new_book_path %></li>
                <li><%= link_to "Add Author", root_path %></li>
                <li><%= link_to "View Authors", root_path %></li>
                <li><%= link_to "Add Publisher", root_path %></li>
                <li><%= link_to "View Publishers", root_path %></li>
                <li><%= link_to "Add Category", new_category_path %></li>
                <li><%= link_to "View Categories", categories_path %></li>
              </ul>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_review.html.erb
<div class="reviews">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>
	<% if user_signed_in? %>
	  <% if review.user_id == current_user.id %>
	    <%= link_to "Edit Review", edit_book_review_path(review.book, review), class: "btn-custom" %>
	    <%= link_to "Delete Review", book_review_path(review.book, review), method: :delete, data: {confirm: "Are you sure?"}, class: "btn-custom" %>
	  <% end %>
	<% end %>
</div>

app/views/reviews/_reviews-form.html.erb
<div class="new-review-form">
	<h1>New Review</h1>
	<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
		<div id="rating-form">
			<label>Rating:</label>
		</div>
	  <%= f.input :comment %>
	  <%= f.button :submit, class: "btn-custom" %>
	<% end %>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@book, @review]) do |f| %>
  <div id="rating-form">
		<label>Rating:</label>
	</div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<%= render 'reviews-form' %>